# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-16 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtaa', '0005_auto_20190116_1656'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hood',
            old_name='admin',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='business',
            name='b_photo',
            field=models.ImageField(null=True, upload_to='business/'),
        ),
    ]
