# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-17 07:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mtaa', '0007_auto_20190116_1920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='poster',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
